### ISSUE TITLE
I have a question, and a sugestion for Resource Hacker

### ISSUE THREAD

**Issue by Dhyfer1** [AngusJohnson/SvgShellExtensions#1]
Hi @AngusJohnson 

I have found that using your dll file my svg images load very fast. I used to use Microsoft PowerToys to view my svg files, but it is very slow loading svg's, so I use SvgShellExtensions and I like it.

My question is: is there any way to remove the browser icon that appears in the bottom right corner of the svg file?

I also like your Resource Hacker software, I use it often. Since the last version 5.1.8, Resource Hacker has not received updates in over a year and a half. I would like to see RH with a new look, such as a dark theme and also icons with material or fluent design. What do you think about that?

**Comment by AngusJohnson** [comment]
> My question is: is there any way to remove the browser icon that appears in the bottom right corner of the svg file?

I think the only way to do that is to remove the association to a default application (ie the application that reads the SVG file when you double-click it).

> Resource Hacker has not received updates in over a year and a half.

I currently have no plans to update Resouce Hacker.

**Comment by Dhyfer1** [comment]
> I think the only way to do that is to remove the association to a default application (ie the application that reads the SVG file when you double-click it).

Okay, I think I can do that.

> I currently have no plans to update Resouce Hacker.

Oh, that's ok. No problem, Resource Hacker has been a great help to me, thanks for replying.

Good day 👍
