### ISSUE TITLE
Write batch scripts for installation and uninstallation

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [AngusJohnson/SvgShellExtensions#4]
Thanks for your extension, but not every user have enough knowledge to register or unregister this extension into system. If you write batch files (.bat or .cmd) for this extension, it’s possible to automatically do so without requiring additional technique, and you can make the script be able to directly ask privilege from User Account Control (UAC).

**Comment by KrasnayaPloshchad** [comment]
You may can consider to create a folder at `C:\Users\[user name]\AppData\Local\` to install, which could potentially eliminate necessary to ask UAC.

**Comment by AngusJohnson** [comment]
Done. See the latest release.
