### ISSUE TITLE
Not working with svgs that contain "image/png" data urls

### ISSUE THREAD

**Issue by bth123** [AngusJohnson/SvgShellExtensions#6]
It shows them as black rectangle
![image](https://github.com/user-attachments/assets/4da98abd-8c80-4028-a1ea-b185a4b41f85)
so here's the svg from screenshot
![assets](https://github.com/user-attachments/assets/cac3b812-b448-472c-bde4-bbd646bd54a9)

**Comment by KrasnayaPloshchad** [comment]
So what will happen if you got SVGs from these sources?
https://commons.wikimedia.org/wiki/Category:SVG_images_with_embedded_raster_graphics
https://commons.wikimedia.org/wiki/Category:Fake_SVG

**Comment by AngusJohnson** [comment]
The recently updated shell extension will handle some (including the SVG in @bth123 's post), but not all embedded images.
